name: Daily Crypto Data Generation

on:
  schedule:
    # Runs daily at 6:00 AM Eastern Time (11:00 AM UTC during EST, 10:00 AM UTC during EDT)
    # Using 10:00 AM UTC to handle both EST and EDT automatically
    - cron: '0 10 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    - name: Install dependencies (lock-file aware)
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          echo "Detected package-lock.json - running npm ci"
          npm ci
        elif [ -f yarn.lock ]; then
          echo "Detected yarn.lock - running yarn install --frozen-lockfile"
          corepack enable || true
          yarn install --frozen-lockfile
        else
          echo "No lock file found - running npm install"
          npm install
        fi
      
    - name: Generate crypto market data
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: node scripts/generate-daily-data.js
      
    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily crypto data update - $(date +'%Y-%m-%d')"
          git push
        fi
